[global]
log-level = "warn"

[repository]
repository = "opendal:sftp"
password-command = "op read op://Private/356hlpxdh5r7byu6ok7otoxf64/password"

[repository.options]
endpoint = "u407515.your-storagebox.de"
root = "/PbZYPXrhdXB8ws3-restic"
user = "u407515-sub6"

[backup]
host = "Motosumo-M1"
git-ignore = true
one-file-system = true

[[backup.snapshots]]
sources = ["/Users/askielboe/work"]

