# Include selected Library folders
Library/*
!Library/Messages
!Library/Mobile Documents
!Library/Calendars
!Library/Keychains
!Library/Preferences
!Library/Scripts
!Library/Application Support/1Password
!Library/Application Support/AddressBook
!Library/Application Support/CloudDocs

# exclude caches and temporary files
.DS_Store
.pytest_cache
*cache*
Cache.noindex
Caches
PersistentCache
BrowserCache
Cache
tmp

# exclude build files and simulators
_build
.android
.cargo
.cocoapods
.dropbox
.flipper
.gem
.gradle
.local
.mix
.node-gyp
.npm
.nvm
.pyenv
.rbenv
.runelite
.rustup
.terraform
.venv
.vscode-server
.vscode/extensions
.yarn
.zprezto
*.pyc
build
node_modules
Pods
site-packages
test_reports
vendor/bundle
venv

# exclude podman containers
.local/share/containers

# exclude data
*.hdf5
*.ldb
*.pb

# exclude logs
*.log*

# exclude binaries
steamapps
XIV on Mac

# exclude downloads and trash
Downloads
Trash
.Trash
